- generator_test.go
That's a test that demonstrates the original problem with V4 only being partially filled with random data
> Add a unit-test to check that V4 reads from PRNG fully

- generator.go
Use io.ReadFull to read data from g.rand instead of a single Read call.
> generator: ensure reads from g.rand are not short

- fuzz.go
Fuzz FromString using github.com/dvyukov/go-fuzz. FromString calls
(*UUID).UnmarshalText, so this test touches all of the places where
package uuid might parse interesting user input.
Since the initial encoding of the UUID is lost when parsed, we cannot
do any better than a simple valid/invalid test.
Updates #2.
> add fuzz test for FromString

- README.md
> fix package URLs in README.md

- codec.go
- generator.go
Fixes name of variable which does not follow Go convention (minor).
Fixes bug where error shadowing causes a hardware address get error to be ignored (major).
> Fix issues found by linter.

- generator.go
It was decided that DefaultGenerator should be exported because the pattern of NewVx() functions was similar to patterns in Go standard library packages (http.DefaultClient, flag.CommandLine, etc.). These standard library packages export their defaults. It is also impractical to write testable code using the UUID library without writing a custom Generator to wrap the NewVx() functions without this interface being exported.
> Export DefaultGenerator (formerly generator).

- README.md
This updates the `README.md` file to improve the grammar and phrasing of certain
sentences, as well as to be more precise or provide clarifications where needed.
This also adds a section to point to the origin of this
repo (`github.com/satori/go.uuid`) and mentions why the fork happened.
This also introduces a new License and Go Report Card badge at the top of the
file.
> Update the README file to have better grammar, and more useful info

- codec.go
As per the https://github.com/gofrs/uuid/issues/23 poll I removed the named return values, which happen to exist only in a single file.
> Remove named return values

- codec_test.go
The `TestDecodePlainWithWrongLength` runs unexported method since there is no other way to reach that line.
It's a substitution for the https://github.com/gofrs/uuid/pull/22 which I accidentally closed via deleting my branch (instead of hard-push'ing it)
> Covered UUID.decodePlain() with wrong input with a test

- codec.go
- generator.go
- uuid.go
This updates the package comments in different areas to improve the GoDoc
rendering of the documentation.
Fixes #27
> Update package comments to provide better documentation

- README.md
Anything less than v2.0.0 is known to have some deficiencies, so this updates
the README to recommend consumers use 2.0.0+.
v2.0.0 needs to be released after merging this change.
> Recommend that people use v2.0.0+ in the README

- uuid.go
This change makes some improvements to the Equal package function:
- updates function comment to read better
- changes the argument variables to `a` and `b`, instead of `u1` and `u2`
- compare the arrays directly, instead of converting to slices and comparing
Fixes #33
> Improve Equal package function

- uuid.go
This deprecates the `Equal` package function, in favor of consumers using the
`==` comparison operator themselves between two `UUID` values. Because the UUID
value is an array type, there is no reason for the helper function.
The intent is to remove this as part of a v2.x => v3.x release.
Fixes #35
> Deprecate the Equal package function

- sql.go
- sql_test.go
This commit adapts satori/go.uuid#44 for our fork of the
original project. This brings JSON Marshaling and Unmarshaling to the
`uuid.NullUUID` type used for use with SQL databases.
This is needed because `uuid.NullUUID` is a shim around `uuid.UUID`, providing
the information needed by the `database/sql` package to support storing the
value in a nullable column. Without these methods, the type gets converted
unnecessarily to a different format than the standard `uuid.UUID` type.
> Add JSON (Un)marshaling methods on NullUUID type

- uuid.go
- uuid_test.go
Because the `Equal` function provided no value, we decided to remove it at the
time of the 2.1.0 release. This change actions that removal to prepare for the
v3.0.0 release.
Fixes #37
> Remove the deprecated Equal function (in preparation for v3.0.0)

- uuid.go
- uuid_test.go
These methods can be used to extract time values
from V1 UUIDs
Originally added as https://github.com/satori/go.uuid/pull/50
> Add Time() and Nanos() methods

- codec.go
Drop unnecessary slice since type is already a slice.
> Tiny code simplification in codec

- sql.go
- sql_test.go
Type UUID can not used as primary key, which is not NULL in table. Type
NullUUID can be used as reference to the primary key in another table,
which may be NULL. If we use jinzhu/gorm to implement the usage
scenario, jinzhu/gorm convert UUID to NullUUID via NullUUID Scan
call. Without the fix below error may be found: uuid: cannot convert
uuid.UUID to UUID.
This fix changes (*UUID) scan to accept UUID argument.
> Change (*UUID) Scan to accept type UUID argument

- .travis.yml
Should we also drop support for older(pre 1.10) versions? 
They're not patched nor supported anymore.
> Use the latest Go releases

- README.md
- go.mod
Remove go.mod and add notes to README.md indicating opt-out for Go 1.11 Modules.
This PR probably also resolves #61, but not to the satisfaction of the original submitter.  After much discussion, it's actually not supported to have a single import path for both module-aware and module-unaware consumers for v2+ packages.
> Remove support for Go 1.11 modules

- .travis.yml
Since uuid doesn't use go mods, this env var is unnecessary. go modules is set to work by default (without setting any env var) after 1.13.
> Remove GO111MODULE from travis CI

- .travis.yml
Add Go 1.12 to the build pipeline.
> Add Go 1.12 releases to the travic CI yml

- README.md
- generator.go
- generator_test.go
- uuid.go
This change removes our support for generating V2 UUIDs from the package, since
it seems that the current implementation is not up to spec in relation to the
DCE 1.1 Specification[1][2].
In our implementation the data written in to the V1, V3-V5 UUID uses Big Endian
byte order as specified in RFC-4122[3]. However, when looking at the DCE
specification they make it read like the data should be written in not Little
Endian but a format where you completely reverse the bites of the value from
most significant first to least significant first:
> Set the time_low field equal to the least significant 32-bits (bits numbered
> 0 to 31 inclusive) of the time stamp in the same order of significance. If a
> DCE Security version UUID is being created, then replace the time_low field
> with the local …
> Remove support for DCE Security UUID (V2) generation

- uuid.go
- uuid_test.go
Adding an IsZero method to uuid.
#92
> adding IsNil method to uuid

- README.md
Updates README to call out experimental v6 and v7 uuid generation functions.
> update readme to document experimental v6 and v7 ids

- README.md
- generator.go
- generator_test.go
- uuid.go
Currently, UUIDv6 and UUIDv7 implementations follow RFC draft rev 02 [1].
However, it has already been updated by RFC draft rev 03 [2] in March 2022.
Rev3 updates v6 and v7 and v8 specifications, but the v6 changes seem to
have no impact on implementation. Therefore, v6 and (unimplemented) v8 are
not affected, so only the UUIDv7 implementation will be updated.
[1] https://datatracker.ietf.org/doc/html/draft-peabody-dispatch-new-uuid-format-02
[2] https://datatracker.ietf.org/doc/html/draft-peabody-dispatch-new-uuid-format-03
In rev 03, complex sequences and variable precision timestamps have been removed from the specification.
The implementation is now simple and lock-free. It looks good.
This PR has breaking changes to the signature of the exported function `NewV7()` and `Gen.NewV7()` , …
> update UUIDv7 implementation with RFC Draft Rev 03 spec

- generator.go
The following PR makes use of UnixMill() to get milli-precision timestamps.
https://github.com/gofrs/uuid/pull/99
UnixMill() was added in go1.17, so it seems that the latest gofrs/uuid is not available from older versions of go.
According to [Go's release policy](https://go.dev/doc/devel/release#policy), the last two versions of go are supported.
Therefore, I don't think it is a critical issue that it is not available for go versions older than go1.16.
However, since we expect some users to use older versions of go, we thought it would be better to stop using UnixMill().
> stop using UnixMill() to make legacy versions compatible

- codec.go
- codec_test.go
- sql.go
- sql_test.go
- uuid.go
- uuid_test.go
This commit improves the performance and reduces the number of allocs of
most UUID methods and adds a new UUID.Parse() method for parsing string
encoded UUIDs.
Parsing string encoded UUIDs is now 2x faster and no longer allocates.
The NullUUID MarshalJSON() and UnmarshalJSON() methods have also been
improved and no longer call out to json.Unmarshal. The UUID.Format
method has been improved for common cases.
Benchmark results:
```
goos: linux
goarch: amd64
pkg: github.com/gofrs/uuid
cpu: Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
name                        old time/op    new time/op    delta
UnmarshalText/canonical-16    47.7ns ± 0%    22.3ns ± 0%   -53.26%  (p=0.000 n=8+10)
UnmarshalText/urn-16          47.8ns ± 1%    22.3ns ± 0%   -53.32%  (p=0.000 n=10+10)
UnmarshalText/braced-16 …
```
> improve performance and reduce allocations of UUID methods

- codec.go
- fuzz.go
- uuid.go
Go 1.19 adds doc comments. This commit runs `gofmt` on all the code to update the comments.
https://tip.golang.org/doc/go1.19#go-doc
> all: gofmt with Go 1.19

- .github/workflows/go.yml
Recently I found that a previous change not related to workflows is failing  in my other PR https://github.com/gofrs/uuid/pull/111
It is happening because the package [golang.org/x/tools/cmd/cover](https://pkg.go.dev/golang.org/x/tools/cmd/cover) is no longer active and marked as deprecated, that's why the workflow will fail.
```
Run go get golang.org/x/tools/cmd/cover
go get golang.org/x/tools/cmd/cover
shell: /usr/bin/bash -e {0}
env:
GO111MODULE: auto
GOROOT: /opt/hostedtoolcache/go/1.19.4/x64
cannot find package "golang.org/x/tools/cmd/cover" in any of:
/opt/hostedtoolcache/go/1.19.4/x64/src/golang.org/x/tools/cmd/cover (from $GOROOT)
/home/runner/go/src/golang.org/x/tools/cmd/cover (from $GOPATH)
Error: Process completed with exit code 1.
```
The tests are focused on 1.18 e 1.19  and …
> Remove deprecated coverage pkg

- README.md
- generator.go
- generator_test.go
Updated V7 generator to enforce the monotonic property for ids generated in the same timestamp.
Updated tests and go docs.
> Updated V7 generator to Draft04.

- uuid.go
- uuid_test.go
> implement TimestampFromV7

- uuid.go
> Fix TimestampFromV7 error message

- .github/dependabot.yml
Adds a configuration for Dependabot to group all GitHub Action updates.
> chore: group GitHub Action updates

- uuid.go
> Fix Comment on the the Timestamp.Time() method

- generator_test.go
- uuid.go
- uuid_test.go
Fixes #195.
The use of the `time.Time` method `UnixNanos()` was causing an `int64` overflow (officially an "undefined behavior"), and returning incorrect timestamp values.
There wasn't any good reason for using this function, since the goal is to convert milliseconds to 100-nanosecond intervals, which can be done much more simply with a single multiplication step.
---
This might also provide a slight performance improvement (see https://github.com/gofrs/uuid/issues/128#issuecomment-2106517809), since `time.UnixMilli`, the (unneeded) call to `.UTC()`, and `.UnixNano()` are each doing a fair bit of work internally, and they have all been replaced with a single multiplication.
> Proper timestamp calculation for UUID v7

- codec.go
- codec_test.go
This pulls code from FromBytes and UnmarshalBinary into FromBytesOrNil which reduces the cost of creating a UUID from a byte slice. It also removes an allocation when the UUID is invalid as it no longer generates an error which is discarded. One downside of this approach is that it duplicates the logic from UnmarshalBinary.
```
goos: linux
goarch: amd64
pkg: github.com/gofrs/uuid/v5
cpu: AMD Ryzen 9 5950X 16-Core Processor
│    old.txt     │            new.txt            │
│     sec/op     │    sec/op     vs base         │
FromBytesOrNil/valid-32      3.814n ± 0%    1.118n ± 1%  -70.69% (n=100)
FromBytesOrNil/empty-32   135.3500n ± 0%   0.6514n ± 1%  -99.52% (n=100)
geomean                      22.72n        0.8534n       -96.24%
│   old.txt    │                 new.txt                  │ …
```
> Improve performance of FromBytesOrNil
